sequenceDiagram
  participant participant_findRolledUpDependency as findRolledUpDependency
  participant participant_pairKey as pairKey
  participant_findRolledUpDependency->>participant_pairKey: pairKey()
  participant_pairKey-->>participant_findRolledUpDependency: return
